var img;
var toohigh;
var toolow;
var tooforward;
var toobackward;
var tooleft;
var tooright;
var eightpic;
var zeropic;
var onepic;
var twopic;
var threepic;
var fourpic;
var fivepic;
var sixpic;
var sevenpic;
var ninepic;

var eightpica;
var zeropica;
var onepica;
var twopica;
var threepica;
var fourpica;
var fivepica;
var sixpica;
var sevenpica;
var ninepica;
function setup() {
createCanvas(window.innerWidth,window.innerHeight);
	img = loadImage('https://i.imgur.com/zz8Iq2k.jpg');
	toohigh = loadImage('https://i.imgur.com/wpkBtbt.jpg')
	toolow = loadImage ('https://i.imgur.com/WyQpLl7.jpg');
	tooforward = loadImage('https://i.imgur.com/ZB5HA9L.jpg');
	toobackward = loadImage('https://i.imgur.com/SdyeKck.jpg');
	tooleft = loadImage('https://i.imgur.com/7pgqW1y.jpg');
	tooright = loadImage('https://i.imgur.com/z3Impih.jpeg');
	zeropic = loadImage('https://i.imgur.com/W2gZN03.png');
	onepic= loadImage('https://i.imgur.com/7GrEW8D.jpg');
	twopic= loadImage('https://i.imgur.com/NBvQWw4.jpg');
	threepic= loadImage('https://i.imgur.com/LXxyVhd.jpg');
	fourpic = loadImage('https://i.imgur.com/uxpZTIP.jpg');
	fivepic= loadImage('https://i.imgur.com/9yT8Zxi.jpg');
	sixpic= loadImage('https://i.imgur.com/oke7HYn.jpg');
	sevenpic= loadImage('https://i.imgur.com/2oQKgM3.jpg');
	eightpic = loadImage('https://i.imgur.com/jHIWpsO.png');
	ninepic= loadImage('https://i.imgur.com/okRA1ya.jpg');
	zeropica = loadImage('https://i.imgur.com/vgUbNNu.png');
	onepica = loadImage('https://i.imgur.com/oGGuOaH.png');
	twopica = loadImage('https://i.imgur.com/reTD1Vm.jpg');
	threepica = loadImage('https://i.imgur.com/Fyq5u12.jpg');
	fourpica = loadImage('https://i.imgur.com/P19LrgT.jpg');
	fivepica = loadImage('https://i.imgur.com/bxB5ePF.jpg');
	sixpica = loadImage('https://i.imgur.com/RejtuvC.jpg');
	sevenpica = loadImage('https://i.imgur.com/cW4x3W7.jpg');
	eightpica = loadImage('https://i.imgur.com/GNR48F6.png');
	ninepica = loadImage('https://i.imgur.com/MQ8OU45.jpg');
}